apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secret
type: Opaque
data:
  TELEGRAM_TOKEN: {{ .Values.telegramBot.token | b64enc | quote }}
  EVERNOTE_TOKEN: {{ .Values.evernote.token | b64enc | quote }}
  EVERNOTE_SANDBOX: {{ .Values.evernote.sandbox | b64enc | quote }}