name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build & Push the Docker image
      run:  docker build . --file Dockerfile --tag evernotetelegrambot:latest
    - name: Push to dockerhub
      run:  docker push icevirm1/evernotetelegrambot:latest:latest
